easy_admin:
    # site_name: Plop
    entities:
      # - App\Entity\LinkEntity

      LinkEntity:
        label: Lien
        class: App\Entity\LinkEntity
        list:
          title: 'Liste des liens'
          fields:
            - id
            - {property: label, label: 'Libellé'}
            - {property: isread, label: 'Lu ?'}
            - {property: rating, label: 'Note'}
            - url